// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV3wnxLlc1FtsA81eg0BF9aCHxySjXLH4',
    appId: '1:654336453013:web:ecb1aa1d55d159bad72e9c',
    messagingSenderId: '654336453013',
    projectId: 'quizapp-esdhc',
    authDomain: 'quizapp-esdhc.firebaseapp.com',
    storageBucket: 'quizapp-esdhc.appspot.com',
    measurementId: 'G-LNRYWETQMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDivV940MaWW498iTvSmahTPdS8ALOWdOA',
    appId: '1:654336453013:android:e2d86201501d616ed72e9c',
    messagingSenderId: '654336453013',
    projectId: 'quizapp-esdhc',
    storageBucket: 'quizapp-esdhc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAom9b_nVGz3IQ3qh9o4l-MusokpfSF22k',
    appId: '1:654336453013:ios:9a08699a4e63f576d72e9c',
    messagingSenderId: '654336453013',
    projectId: 'quizapp-esdhc',
    storageBucket: 'quizapp-esdhc.appspot.com',
    iosClientId: '654336453013-5er0efmehrv1du3adfmp1qomfl1e0rs4.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAom9b_nVGz3IQ3qh9o4l-MusokpfSF22k',
    appId: '1:654336453013:ios:9a08699a4e63f576d72e9c',
    messagingSenderId: '654336453013',
    projectId: 'quizapp-esdhc',
    storageBucket: 'quizapp-esdhc.appspot.com',
    iosClientId: '654336453013-5er0efmehrv1du3adfmp1qomfl1e0rs4.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
