// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF4fc_gKVmA2VqLwHRecU4N9CHFy2-as8',
    appId: '1:1016629374785:web:630ff0c59fad0e06cebbc0',
    messagingSenderId: '1016629374785',
    projectId: 'quiz-app-esdhc',
    authDomain: 'quiz-app-esdhc.firebaseapp.com',
    storageBucket: 'quiz-app-esdhc.appspot.com',
    measurementId: 'G-RKF8TR3Z1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWSPsmqNWyUtlS4TJYXAWyyH7vr6Z-ue4',
    appId: '1:1016629374785:android:585abd88a6f74862cebbc0',
    messagingSenderId: '1016629374785',
    projectId: 'quiz-app-esdhc',
    storageBucket: 'quiz-app-esdhc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8rEZ6a6S3cHhsCpGnawES04TgF_7Van4',
    appId: '1:1016629374785:ios:f6afb99d1d065ac6cebbc0',
    messagingSenderId: '1016629374785',
    projectId: 'quiz-app-esdhc',
    storageBucket: 'quiz-app-esdhc.appspot.com',
    iosClientId: '1016629374785-iuiauf2ab62dvli2ungkftrh4v2ku7hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8rEZ6a6S3cHhsCpGnawES04TgF_7Van4',
    appId: '1:1016629374785:ios:f6afb99d1d065ac6cebbc0',
    messagingSenderId: '1016629374785',
    projectId: 'quiz-app-esdhc',
    storageBucket: 'quiz-app-esdhc.appspot.com',
    iosClientId: '1016629374785-iuiauf2ab62dvli2ungkftrh4v2ku7hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
